### ISSUE TITLE
Represent every subtraction with an addition and a negation

### ISSUE THREAD

**Issue by hexawyz** [GoldenCrystal/SolidSharp#1]
* x - y becomes ````x + (-y)````
* ````x + (-y)```` stays ````x + (-y)````

Advantages:
* Same code path for addition and subtraction
* Less duplication of code
* No weird differences between subtractions and negations

**Comment by GoldenCrystal** [comment]
Done: https://github.com/GoldenCrystal/SolidSharp/commit/65f5820a0cb4366abf5e0fff14bff3ddb1a9dd7b
